sudo: required

# trusty required for docker
# https://github.com/travis-ci/travis-ci/issues/5448
dist: trusty

services:
  - docker

language: go

matrix:
  include:
    - go: 1.6

addons:
  apt:
    packages:
      - rpm

cache:
  apt: true
  directories:
    - tools

install:
  - source scripts/travis-cache.sh

script:
  - mkdir -p /tmp/out
  - ./scripts/ci_build.py

after_failure:
  - tail logs/*

before_deploy:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/bash scripts/bintray.sh /tmp/out
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: /bin/bash scripts/docker.sh
    on:
      branch: master
