---
name: kubernetes
version: 1.3.0-alpha.1.1925-2dde8e9607d49f
license: ASL 2.0
iteration: 6
vendor: Google
architecture: x86_64
url: http://kubernetes.io/
description: Automated container deployment, scaling, and management
type: rpm

targets:
  - src: '{{.BuildRoot}}/out/kubectl'
    dest: /usr/bin/
  - src: '{{.BuildRoot}}/out/kubelet'
    dest: /usr/bin/

scripts:
  build: |
    {{includeTemplate (specFile "build.sh")}}

extra-args: |
  --rpm-os linux
  --rpm-auto-add-directories
